import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import { existsSync } from "node:fs"

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    devGuide: [{ type: "autogenerated", dirName: "devGuide" }],
    devDesign: [{ type: "autogenerated", dirName: "devDesign" }],
    devSpecification: [{ type: "autogenerated", dirName: "devSpecification" }],
    adminGuide: [{ type: "autogenerated", dirName: "adminGuide" }],
    userGuide: [{ type: "autogenerated", dirName: "userGuide" }],
}

export default sidebars;
